### ISSUE TITLE
Add basics of classes and objects

### ISSUE THREAD

**Issue by pandayed** [xpandeyed/PythonNotes#2]
The notes still lack the concept of classes and objects. Kindly add notes for them too.

**Comment by akshaykhoje** [comment]
Please assign this issue to me.

**Comment by RahulSankhla312** [comment]
hey @xpandeyed could you assign this issue to me.

**Comment by atharva360** [comment]
can you please assign me this task...

**Comment by ayushigeorge** [comment]
can I contribute by adding basic programs of classes and objects?
